[build]
builder = "nixpacks"
buildCommand = "bash build.sh"

[deploy]
startCommand = "bash start.sh"
healthcheckPath = "/healthz"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
